# Example configuration file (backend/config.yaml)
# Use environment variables for secrets in production!

# Server settings
SERVER_ADDRESS: ":8080"

# Neo4j Database connection
NEO4J_URI: "neo4j://localhost:7687"
NEO4J_USER: "neo4j"
NEO4J_PASSWORD: "password"  # <-- Use ENV VAR in production!

# OpenAI API settings
OPENAI_API_KEY: "sk-..."  # <-- Use ENV VAR in production!
EMBEDDING_MODEL_ID: "text-embedding-3-small" # Or "text-embedding-ada-002" etc.

# Paths to external CLI tools
SITE_BUILDER_PATH: "/usr/local/bin/site-builder" # Adjust path as needed
WALRUS_CLI_PATH: "/usr/local/bin/walrus"       # Adjust path as needed

# Seal Access Control settings
SEAL_API_KEY: "seal_api_key_..."  # <-- Use ENV VAR in production!
SEAL_ENDPOINT: "https://api.seal.xyz" # Verify the correct endpoint

# Sui Blockchain Interaction settings
SUI_RPC_ENDPOINT: "https://fullnode.devnet.sui.io:443" # Example for Sui Devnet
SUI_NETWORK: "devnet"                                # Options: devnet, testnet, mainnet
# IMPORTANT: Replace with your actual event type string from your Move contract
SUI_SITE_DEPLOYED_EVENT_TYPE: "0xYOUR_PACKAGE_ID::YOUR_MODULE::SiteDeployed"

# SUINS Integration settings
# IMPORTANT: Replace with the actual addresses/types for the SUINS system you use
SUINS_CONTRACT_ADDRESS: "0xEXAMPLE_SUINS_REGISTRY_PACKAGE_ID"
SUINS_NFT_TYPE: "0xEXAMPLE_SUINS_REGISTRY_PACKAGE_ID::suins::Suins" # Example Type